/*
 * This source file was generated by the Gradle 'init' task
 */
package org.hibernate.omm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
    }
}
