/*
 * This source file was generated by the Gradle 'init' task
 */
package org.hibernate.omm;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class LibraryTest {
  @Test
  void someLibraryMethodReturnsTrue() {}
}
